"""add login sys

Revision ID: 292d4a0bc3fa
Revises: 
Create Date: 2024-12-03 15:58:25.353222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292d4a0bc3fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
